name: Test CDK and App when pushing to main

on:
  push:
    branches:
      - main

jobs:
  test_cdk:
    name: CDK
    uses: ./.github/workflows/test_cdk.yml
  test_app:
    name: App
    uses: ./.github/workflows/test_app.yml