name: Test CDK and App when pushing to main

on:
  push:
    branches:
      - main


jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/bake-action@v2
        with:
          files: |
            ./docker-compose.yml
          targets: poetry
          load: true
          set: |
            *.context=.
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=min
      - run: |
          ls .