name: Test CDK and App when pushing to main

on:
  push:
    branches:
      - main

jobs:
  poetry:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3
      - uses: ./.github/actions/poetry
