name: Test CDK and App when pushing to main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/on_push_test_cdk.yml
      - uses: ./.github/actions/on_push_test_app.yml
    timeout-minutes: 30