name: Test CDK
on:
  push:
    branches-ignore:
      - main
    paths:
      - cdk/**
  workflow_call:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test CDK
        run: |
          echo "Test"
    timeout-minutes: 10
